#.travis.yml
os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.9"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # - sudo apt-get update
  # - sudo apt-get install -y libappindicator1 fonts-liberation
  # - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  # - sudo dpkg -i google-chrome*.deb

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

# script: ng test --watch=false && ng e2e && ng build --prod #this actually works like a charm.

script: ng build --prod
  # - ng e2e

# after_script:
#   - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: always